name: gorev_yoneticisi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Mevcut paketlerin:
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  confetti: ^0.8.0

  # YENİ EKLENEN HIVE PAKETLERİ (Veritabanı için):
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # YENİ EKLENEN KOD ÜRETİCİLER (Hive Adapter için):
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

# İkon Ayarların (Aynen korundu)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
